package com.menjilearn.crm.settings.mapper;

import com.menjilearn.crm.settings.pojo.User;

import java.util.List;
import java.util.Map;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Sun Jun 19 22:06:27 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Sun Jun 19 22:06:27 CST 2022
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Sun Jun 19 22:06:27 CST 2022
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Sun Jun 19 22:06:27 CST 2022
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Sun Jun 19 22:06:27 CST 2022
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Sun Jun 19 22:06:27 CST 2022
     */
    int updateByPrimaryKey(User record);

    /**
     * 根据用户数据的账号的密码查询用户是否存在
     * @param loginActAndLoginPwdMap
     * @return
     */
    User queryUserByLoginActAndLoginPwd(Map<String,Object> loginActAndLoginPwdMap);

    /**
     * 查询所有用户的信息
     * @return
     */
    List<User> selectAllUsers();
}